[package]
name = "wallet_fingerprinting"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bitcoincore-rpc = "0.15.0"
bitcoin = "0.28.1"
